(define (sqtr x)
	(define (good-enough? guess x)
		(< (abs (- (square guess) x)) 0.001))
	(define (imporve guess)
		(average guess (/ x guess)))
	(define (average a b)
		(/ (+ a b) 2))
	(define (sqrt-iter guess)
		(if (good-enough? guess)
		guess
		(sqrt-iter (imporve guess))))	
(sqrt-iter 1.0))
